# Generated by Django 2.0.6 on 2018-07-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=8, unique=True)),
                ('airlines_id', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('departure', models.TimeField()),
                ('arrival', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Users'),
        ),
    ]
