# Generated by Django 2.0.6 on 2018-07-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='flight_num',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, to='first.Airlines'),
        ),
    ]
